[project]
site_name = "serialx"
site_description = "Serial communication library for Linux, macOS, and Windows."
site_author = "puddly"
copyright = """
Copyright &copy; 2026 serialx contributors
"""
nav = [
    { "Overview" = "index.md" },
    { "Installation" = "installation.md" },
    { "Usage" = "usage.md" },
    { "Development" = "development.md" },
]

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
