[project]
site_name = "serialx"
site_description = "Serial communication library for Linux, macOS, and Windows."
site_author = "puddly"
copyright = """
Copyright &copy; 2026 serialx contributors
"""
nav = [
    { "Overview" = "index.md" },
    { "Installation" = "installation.md" },
    { "Usage" = "usage.md" },
    { "API: Core" = "api.md" },
    { "API: POSIX" = "api/platforms/posix.md" },
    { "API: Extended POSIX" = "api/platforms/extended-posix.md" },
    { "API: Linux" = "api/platforms/linux.md" },
    { "API: macOS" = "api/platforms/darwin.md" },
    { "API: FreeBSD" = "api/platforms/freebsd.md" },
    { "API: Windows" = "api/platforms/win32.md" },
    { "API: Socket" = "api/platforms/socket.md" },
    { "API: RFC2217" = "api/platforms/rfc2217.md" },
    { "API: ESPHome" = "api/platforms/esphome.md" },
    { "Development" = "development.md" },
]

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["serialx"]

[project.plugins.mkdocstrings.handlers.python.options]
show_source = false
docstring_style = "google"
inherited_members = true

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
