name: CI

on:
  push:
  pull_request: ~

jobs:
  pytest-windows:
    runs-on: windows-latest
    name: Run tests Python 3.13 (Windows)
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install com0com
        shell: pwsh
        working-directory: .github
        run: |
          Invoke-WebRequest https://github.com/Apollon77/SupportingFiles/raw/a14981be47f3be872a4aec2d989ab529ba362f23/appveyor/serial/com0com.cer -OutFile com0com.cer
          CertMgr.exe /add com0com.cer /s /r localMachine root
          CertMgr.exe /add com0com.cer /s /r localMachine trustedpublisher

          Invoke-WebRequest https://github.com/Apollon77/SupportingFiles/raw/a14981be47f3be872a4aec2d989ab529ba362f23/appveyor/serial/setup_com0com_W7_x64_signed.exe -OutFile setup_com0com_W7_x64_signed.exe
          .\setup_com0com_W7_x64_signed.exe /S
      - name: Configure com0com
        shell: pwsh
        working-directory: C:\Program Files (x86)\com0com
        run: |
          .\setupc.exe --wait 1 install PortName=-,EmuBR=yes,cts=rdtr PortName=-,EmuBR=yes,cts=rdtr
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          pip install -e .[dev] pytest-cov
      - name: Run tests
        shell: pwsh
        run: |
          python -m serialx.tools.list_ports
          pytest --timeout=20 --cov=serialx tests --adapter-pair CNCA0:CNCB0
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-windows-latest
          include-hidden-files: true
          path: .coverage
